force-app/main/default/objects/Chat_Hub_Message__e/Chat_Hub_Message__e.object-meta.xml
<CustomObject>
    <label>Chat Hub Message</label>
    <pluralLabel>Chat Hub Messages</pluralLabel>
</CustomObject>

force-app/main/default/objects/Chat_Hub_Message__e/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <label>Text</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MessagePublisher.cls
/**
 * Created by AlehZhuk on 10/25/2023.
 */

public with sharing class MessagePublisher {

    @AuraEnabled
    public static void publish(String messageText) {
        Chat_Hub_Message__e event = new Chat_Hub_Message__e(Text__c = messageText, User_Name__c = UserInfo.getLastName());
        Database.SaveResult res = EventBus.publish(event);
        if (res.success) {
            System.debug(res.id);
        } else {
            for (Database.Error error: res.errors) {
                System.debug(error.getMessage());
            }
        }
    }
}