force-app/main/default/objects/Chat_Message__c/Chat_Message__c.object-meta.xml
<CustomObject>
    <label>Chat Message</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chat_Message__c/fields/Message_Text__c.field-meta.xml
<CustomField>
    <fullName>Message_Text__c</fullName>
    <label>Message Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chat_Message__c/fields/Readed__c.field-meta.xml
<CustomField>
    <fullName>Readed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Readed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Chat_Message__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Edit</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MessageMapper.cls
/**
 * Created by AlehZhuk on 10/26/2023.
 */

public with sharing class MessageMapper {
    public static ChatMessage toDomain(Chat_Message__c message) {
        ChatMessage domain = new ChatMessage();
        domain.id = message.Id;
        domain.name = message.Name;
        domain.text = message.Message_Text__c;
        domain.status = message.Status__c;
        domain.isRead = message.Readed__c;
        domain.createdDate = message.Created_Date__c;
        domain.ownerId = message.OwnerId;
        return domain;
    }

    public static List<ChatMessage> toDomains(List<Chat_Message__c> messages) {
        List<ChatMessage> domains = new List<ChatMessage>();
        for (Chat_Message__c message: messages) {
            domains.add(toDomain(message));
        }
        return domains;
    }
}